apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-platform-config
  labels:
    {{- include "k6-platform.labels" . | nindent 4 }}
data:
  INFLUXDB_URL: {{ .Values.influxdb.url | quote }}
  INFLUXDB_ORG: {{ .Values.influxdb.org | quote }}
  INFLUXDB_BUCKET: {{ .Values.influxdb.bucket | quote }}
  POSTGRES_HOST: {{ .Values.postgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  MOCK_SERVER_URL: "http://mock-server:{{ .Values.mockServer.service.port }}"
  K6_RUNNER_BASE_URL: "http://k6-runner:{{ .Values.k6Runner.service.port }}"
  K6_DASHBOARD_URL: "http://k6-runner:{{ .Values.k6Runner.service.dashboardPort }}"
