{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  labels:
    {{- include "k6-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ .Values.postgresql.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.postgresql.secretKeys.username }}
      remoteRef:
        key: {{ .Values.externalSecrets.postgresql.remoteKey | quote }}
        property: {{ .Values.externalSecrets.postgresql.usernameProperty | quote }}
    - secretKey: {{ .Values.postgresql.secretKeys.password }}
      remoteRef:
        key: {{ .Values.externalSecrets.postgresql.remoteKey | quote }}
        property: {{ .Values.externalSecrets.postgresql.passwordProperty | quote }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-token
  labels:
    {{- include "k6-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ .Values.influxdb.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.influxdb.secretKeys.token }}
      remoteRef:
        key: {{ .Values.externalSecrets.influxdb.remoteKey | quote }}
        property: {{ .Values.externalSecrets.influxdb.tokenProperty | quote }}
{{- end }}
