{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "k6-platform.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "test_admin" | b64enc | quote }}
  password: {{ "testpassword" | b64enc | quote }}
{{- end }}
---
{{- if not .Values.influxdb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-token
  labels:
    {{- include "k6-platform.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ "dev-token-for-testing" | b64enc | quote }}
{{- end }}
