apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: control-panel
type: Opaque
stringData:
  username: test_admin
  password: testpassword