apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.influxdb.token | b64enc }}