apiVersion: v1
kind: Secret
metadata:
  name: influxdb-token
  namespace: k6-platform
type: Opaque
stringData:
  # 로컬 개발용 고정 토큰 (AWS EKS에서는 다른 방법 사용)
  token: "apiv3_1mW0j3glqhna5FRJrI9A0cGZLKybAUfwrnZ2zG70Xciwaet9FOsqeEqELq_7OBqPmPISHhVFgsyquGR4zD0WtQ"