apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: k6-platform
data:
  INFLUXDB_ORG: "k6org"
  INFLUXDB_BUCKET: "k6"
  INFLUXDB_NODE_ID: "influxdb-node-1"
  INFLUXDB_ADMIN_BUCKET: "k6"
  INFLUXDB_ADMIN_ORG: "k6org"
  INFLUXDB_ADMIN_USER: "admin"
  INFLUXDB_ADMIN_PASSWORD: "admin123"
  INFLUXDB_AUTH_ENABLED: "true"
  INFLUXDB3_AUTH_TOKEN: "apiv3_9TZuUxQ8PRJ2QrB2Tg3WLNI9nv-YZJn7Mzef2w7bAkJQ1TK2KhQ5mP-ez-NDywrm_TguVWiZ_KoyHVUU9A9_7A"
  INFLUXDB_ADMIN_TOKEN: "apiv3_9TZuUxQ8PRJ2QrB2Tg3WLNI9nv-YZJn7Mzef2w7bAkJQ1TK2KhQ5mP-ez-NDywrm_TguVWiZ_KoyHVUU9A9_7A"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: k6-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: k6-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      nodeSelector:
        workload: main-services
      containers:
        - name: influxdb
          image: bitnami/influxdb:3.3.0-debian-12-r34
          ports:
            - containerPort: 8181
          envFrom:
            - configMapRef:
                name: influxdb-config
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: k6-platform
spec:
  selector:
    app: influxdb
  ports:
    - port: 8181
      targetPort: 8181
  type: ClusterIP
